#!/bin/bash

sudo apt-get update -y
sudo apt-get full-upgrade -y

sudo apt install openjdk-17-jre -y

# add vars
sudo nano /etc/environment
INFRAMACHINE_DB_URL="someurl"
INFRAMACHINE_DB_PASSWORD="somepass"
INFRAMACHINE_DB_USER="someuser"
INFRAMACHINE_IMAGES_URL="someurl"
source /etc/environment

# create project
sudo git clone https://github.com/victordalosto/ai-trainer.git /app

sudo chmod +x /app/mvnw
cd /app
sudo ./mvnw clean package
screen -dm sudo ./mvnw spring-boot:run

## To kill last screen: 
# screen -ls
# screen -r <code>